* 
* 
*     _    __        _      __                           
*    | |  / /____   (_)____/ /_      __ ____ _ _____ ___ 
*    | | / // __ \ / // __  /| | /| / // __ `// ___// _ \
*    | |/ // /_/ // // /_/ / | |/ |/ // /_/ // /   /  __/
*    |___/ \____//_/ \__,_/  |__/|__/ \__,_//_/    \___/ 
*                                                        
*  Copyright (c) 2016-2017 Voidware Ltd.  All Rights Reserved.
* 
*  This file contains Original Code and/or Modifications of Original Code as
*  defined in and that are subject to the Voidware Public Source Licence version
*  1.0 (the 'Licence'). You may not use this file except in compliance with the
*  Licence or with expressly written permission from Voidware.  Please obtain a
*  copy of the Licence at https://strandgames.com/legal/strandPSL1.txt and read
*  it before using this file.
* 
*  THIS IS NOT FREE SOFTWARE.
*  
*  The Original Code and all software distributed under the Licence are
*  distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS
*  OR IMPLIED, AND VOIDWARE HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING
*  WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
*  PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
* 
*  Please see the Licence for the specific language governing rights and 
*  limitations under the Licence.
* 
*  contact@strandgames.com
* 
*  This software was originally written and owned By Magnetic Scrolls Ltd.
*  It is being released under a Public Source Licence for historical reference
*  and educational purposes.
*


******************************************************
*
*	@(#)msgwrite.asm	2.5
*	5/16/87
*
******************************************************

		SECTION		"ADV",CODE

*--------------------------------
*
*  SRC.ADV.MSGWRITE1A  
*
*--------------------------------

	include	"equates.asm"
	include	"macros.asm"

      XREF     PLURAL,P.MSG,PRTTXT,M_STACK

      XDEF     W.THERE,W.HERE,W.HER,W.HIM,W.SHE,W.CNTSEE,W.ASCONT,W.HAPPY
      XDEF     W.YCNDTT,W.YSI,W.UNABLE,W.ITSOFT,W.CGGO,W.BRKS,W.SNPS,W.DBS
      XDEF     W.NHAP,W.IDFY,W.CSTFH,W.BUT,W.WT,W.ON,W.IN,W.HN,W.ICNDTW
      XDEF     W.NOW,W.FXTO,W.DNH,W.ARDY,W.CLSE,W.OPN,W.THEVY,W.NT,W.DBR
      XDEF     W.CTMA,W.SOME,W.NCONT,W.DCONTA,W.FOOL,W.DEAD,W.DROPD,W.TAKEN
      XDEF     W.ALCAR,W.CGTW,W.INW,W.TAKOF,W.CNTS,W.WEARNG,W.2BIG,W.NEF,W.LIT
      XDEF     W.MLTS,W.MELTS,W.EXP,W.NLIT,W.YOU,W.ARE,W.WNTLT,W.ISWEAR,W.SEEMS
      XDEF     W.HNICE,W.PSH,W.BYH,W.CNTGT,W.TTR,W.IN2W,W.WNTF,W.CAR,W.MVG
      XDEF     W.LWG,W.SML,W.LKE,W.RHI,W.YSSR,W.MB,W.DEF0,W.RAN,W.ALRDF
      XDEF     W.DUST,W.I2DARK,W.NOMOUT,W.JNSP,W.JNCP,W.BMSP,W.OTH,W.WHAT
      XDEF     W.BTHE,W.WNHA,W.BZ,W.WRTH,W.THE,W.AN,W.AND,W.IS,W.NTCAR
      XDEF     W.WRSYN,W.VSHP,W.SHP,W.WET,W.NNA,W.OYSB,W.SOFT,W.GOT,W.CON
      XDEF     W.FXTIT,W.ANYT,W.FAPART,W.SEPAWY,W.NOT,W.DFLESS,W.DFND,W.DEFET
      XDEF     W.TSOFT,W.THANK,W.UNCON,W.ASLEP,W.AETARG,W.OFF,W.FINSH,W.LOCKED
      XDEF     W.FUN,W.INTER,W.CRUNCH,W.WNTMVE,W.AHEM,W.CNTHEA

      XDEF     W.FXPERM,W.FITS,W.COP1,W.COP6,W.COP12,W.COP15,W.IFUSAY,W.TAPDCE
      XDEF     W.NOTYET,W.NOTIMP,W.OUTWEI,W.SHIPS,W.RBEARD,W.MUNCH,W.PUFF
      XDEF     W.NEMPTY,W.ONLY,W.ATMOMT,W.IT,W.HE,W.THEY,W.THEM,W.MSTBE
      XDEF     W.HASSLE,W.EH,W.TTHERE,W.SILNT,W.WWAY,W.VPSYC,W.PUTON,W.AYKILL
      XDEF     W.BEATRB,W.CONTO,W.ANYTH,W.TASTES,W.REMOVE,W.NINSID,W.AINSID
      XDEF     W.HITS,W.OUCH,W.WAKES,W.ASLEEP,W.TPASS,W.ANOY,W.FIDDLE,W.GIVEUP
      XDEF     W.NOVEL,W.NMOUTH,W.PUSH,W.TOGTY,W.THEMAL,W.INTOWO,W.NCONCE
      XDEF     W.SAYTO,W.IMPOLI,W.THOUGH,W.HELLO,W.HRD2BE,W.KNOWNO,W.REALWN
      XDEF     W.YDESIR,W.CAREWN,W.FALSEI,W.TRUEI,W.ERROR,W.FERG,W.FOR,W.GIVE
      XDEF     W.FLOOK,W.CANTH,W.NO.TNG,W.REBUIL,W.SOMETH,W.WHICH,W.BTINA
      XDEF     W.ACON,W.NWHERE,W.IDNATA,W.SAYS,W.PLUSE,W.MAD,W.HYF,W.NOIDEA
      XDEF     W.WYLTK,W.NOTOBV,W.STQ,W.IDNK,W.BECOF,W.BECAUS,W.EMMM,W.TNNICE
      XDEF     W.FSALE,W.AYOURS,W.NTENDE,W.STRANG,W.NDEAL,W.SO,W.PUT,W.ONGND
      XDEF     W.CNTCAR,W.TO,W.LIGHT,W.IDNTT,W.QSUIT,W.CNTUNL,W.STEADF,W.APEARS
      XDEF     W.2MUCH,W.CLOSED,W.1ATTIM,W.ROPED,W.TEAR,W.SHRED,W.TOO,W.TOUGH
      XDEF     W.ENOUGH,W.STRONG,W.NOCUT,W.NEASY,W.MINDRD,W.NTREAD,W.CANCOP
      XDEF     W.OR,W.SHUTUP,W.MBEITI,W.ITSGOD,W.YURMIS,W.MYPROB,W.ALWAYS
      XDEF     W.VERYWE,W.NONE,W.NOTMUC,W.IHAVNT,W.POSSIB,W.UNLIKE,W.NOCHAN
      XDEF     W.NOTREA,W.NEVER,W.ISPOSS,W.IDKYC,W.ASKSOM,W.SLIM,W.DONTWR

      XDEF     W.FUTURE,W.WLATER,W.DWAM,W.DEV,W.RIGHTS,W.SHOULD,W.ISNTRE,W.TWBT
      XDEF     W.INTHAI,W.GQUEST,W.FORGOT,W.UNLOCK,W.NWAY,W.IAM,W.WEIRD
      XDEF     W.GOTNON,W.BIDHIT,W.NONEED,W.JSTWHT,W.CLICK,W.SQLCH,W.THUD
      XDEF     W.FNOI,W.HFUN,W.BROKEN,W.GIVESP,W.ABSKIS,W.JUSONE,W.NOTIE
      XDEF     W.NORCH,W.FHERE,W.NOTAKE,W.NORIDE,W.WHAK,W.FALOFF,W.TALKME
      XDEF     W.ALRDY,W.YBLUKY,W.TRICKQ,W.MTMAGI,W.NOTSEA,W.ONFEET,W.NSO
      XDEF     W.CSOT,W.CSJA,W.NOLIE,W.SITUP,W.ASO,W.NOSEAT,W.CTEXT,W.ONEOF
      XDEF     W.GLARE,W.MAGFOR,W.LEAP,W.HAS,W.VANI,W.DEADDN,W.IFONLY
      XDEF     W.BURNAW,W.DEADED,W.LETOFF,W.PDR2,W.USURE,W.QUIT,W.ENSURE
      XDEF     W.IAGREE,W.4BUFS,W.JCHKG,W.WISLI,W.NO,W.MINE,W.FIND,W.GETOFF
      XDEF     W.NOTMY,W.THIEF,W.WPRI,W.COULD,W.ABOUT,W.WORTH,W.WLESS,W.PROBAB
      XDEF     W.OFANY,W.ME,W.PLESS,W.BADW,W.HOHO,W.UMEAN,W.TEMPTR,W.IYAUPT
      XDEF     W.ICDOAN,W.GLOW,W.NOONE

W.THERE      PEA    W.GNUM2+2(PC)   ;FUDGE STACK FOR BODGE
               BRA.S  W.GNUM4
W.HERE       PEA    W.GNUM2+4(PC)   ;FUDGE STACK FOR BODGE
               BRA.S  W.GNUM4
W.HER        PEA    W.GNUM3+2(PC)   ;FUDGE STACK FOR BODGE
               BRA.S  W.GNUM4
W.HIM        PEA    W.GNUM3+4(PC)   ;FUDGE STACK FOR BODGE
               BRA.S  W.GNUM4
W.SHE        PEA    LBL.SHE+2(PC)     ; FUDGE STACK
               BRA.S  W.GNUM4
W.CNTSEE     PEA    LBL.CNTSEE+2(PC)  ; FUDGE STACK
               BRA.S  W.GNUM4
W.ASCONT     PEA    W.GNUM6+2(PC)
               BRA.S  W.GNUM4
W.HAPPY      PEA    W.GNUM6+4(PC)
W.GNUM4
               BRA    W.GNUM
  
W.GNUMSTART
       
W.YCNDTT   CALL_S	W.GNUM2
W.YSI      CALL_S	W.GNUM2
W.UNABLE   CALL_S	W.GNUM2
W.ITSOFT   CALL_S	W.GNUM2
W.CGGO     CALL_S	W.GNUM2
W.BRKS     CALL_S	W.GNUM2
W.SNPS     CALL_S	W.GNUM2
W.DBS      CALL_S	W.GNUM2
W.NHAP     CALL_S	W.GNUM2
W.IDFY     CALL_S	W.GNUM2
W.CSTFH    CALL_S	W.GNUM2
W.BUT      CALL_S	W.GNUM2
W.WT       CALL_S	W.GNUM2
W.ON       CALL_S	W.GNUM2
W.IN       CALL_S	W.GNUM2
W.HN       CALL_S	W.GNUM2
W.ICNDTW   CALL_S	W.GNUM2
W.NOW      CALL_S	W.GNUM2
W.FXTO     CALL_S	W.GNUM2
W.DNH      CALL_S	W.GNUM2
W.ARDY     CALL_S	W.GNUM2
W.CLSE     CALL_S	W.GNUM2
W.OPN      CALL_S	W.GNUM2
W.THEVY    CALL_S	W.GNUM2
W.NT       CALL_S	W.GNUM2
W.DBR      CALL_S	W.GNUM2
W.CTMA     CALL_S	W.GNUM2
*W.NEDBL    CALL_S	W.GNUM2
*W.POIS     CALL_S	W.GNUM2
*W.SICK     CALL_S	W.GNUM2
*W.ILL      CALL_S	W.GNUM2
*W.EDBL     CALL_S	W.GNUM2
*W.GOOD     CALL_S	W.GNUM2
*W.VGOOD    CALL_S	W.GNUM2
*W.MGCL     CALL_S	W.GNUM2
       
       DS.B     2*8
 
W.SOME     CALL_S	W.GNUM2
*W.ANY      CALL_S	W.GNUM2
  
       DS.B     2
  
W.NCONT    CALL_S	W.GNUM2
W.DCONTA   CALL_S	W.GNUM2
W.FOOL     CALL_S	W.GNUM2
W.DEAD     CALL_S	W.GNUM2
W.DROPD    CALL_S	W.GNUM2
W.TAKEN    CALL_S	W.GNUM2
W.ALCAR    CALL_S	W.GNUM2
W.CGTW     CALL_S	W.GNUM2
W.INW      CALL_S	W.GNUM2
*W.JMP      CALL_S	W.GNUM2
*W.VLT      CALL_S	W.GNUM2
  
       DS.B     2*2
       
W.TAKOF    CALL_S	W.GNUM2
W.CNTS     CALL_S	W.GNUM2
W.WEARNG   CALL_S	W.GNUM2
W.2BIG     CALL_S	W.GNUM2
W.NEF      CALL_S	W.GNUM2
W.LIT      CALL_S	W.GNUM2
W.MLTS
W.MELTS    CALL_S	W.GNUM2
W.EXP      CALL_S	W.GNUM2
W.NLIT     CALL_S	W.GNUM2
W.YOU      CALL_S	W.GNUM2
W.ARE      CALL_S	W.GNUM2
LBL.CNTSEE     NOP             ;CAN'T CALL_STO NEXT INST 
*W.THERE    CALL_S	W.GNUM2
W.GNUM2    BRA    W.GNUM
*W.HERE     CALL_S	W.GNUM2
W.WNTLT    CALL_S	W.GNUM2
W.ISWEAR   CALL_S	W.GNUM2
W.SEEMS    CALL_S	W.GNUM2
W.HNICE    CALL_S	W.GNUM2
W.PSH      CALL_S	W.GNUM2

*--------------------------------
*
*  SRC.ADV.MSGWRITE1B  
*
*--------------------------------
 
W.BYH      CALL_S	W.GNUM2
W.CNTGT    CALL_S	W.GNUM2
W.TTR      CALL_S	W.GNUM2
W.IN2W     CALL_S	W.GNUM2
W.WNTF     CALL_S	W.GNUM2
W.CAR      CALL_S	W.GNUM2
W.MVG      CALL_S	W.GNUM2
W.LWG      CALL_S	W.GNUM2
W.SML      CALL_S	W.GNUM2
W.LKE      CALL_S	W.GNUM2
W.RHI      CALL_S	W.GNUM2
W.YSSR     CALL_S	W.GNUM2
W.MB       CALL_S	W.GNUM2
W.DEF0     CALL_S	W.GNUM2
W.RAN      CALL_S	W.GNUM2
W.ALRDF    CALL_S	W.GNUM2
W.DUST     CALL_S	W.GNUM2
W.I2DARK   CALL_S	W.GNUM2
W.NOMOUT  CALL_S	W.GNUM2
W.JNSP     CALL_S	W.GNUM2
W.JNCP     CALL_S	W.GNUM2
W.BMSP     CALL_S	W.GNUM2
W.OTH      CALL_S	W.GNUM2
W.WHAT     CALL_S	W.GNUM2
W.BTHE     CALL_S	W.GNUM2
W.WNHA     CALL_S	W.GNUM2
W.BZ       CALL_S	W.GNUM2
W.WRTH     CALL_S	W.GNUM2
W.THE      CALL_S	W.GNUM2
W.AN       CALL_S	W.GNUM2
W.AND      CALL_S	W.GNUM2
W.IS       CALL_S	W.GNUM2
W.NTCAR    CALL_S	W.GNUM2
W.WRSYN    CALL_S	W.GNUM2
W.VSHP     CALL_S	W.GNUM2
W.SHP      CALL_S	W.GNUM2
W.WET      CALL_S	W.GNUM2
W.NNA      CALL_S	W.GNUM2
W.OYSB     CALL_S	W.GNUM2
*W.SMTH     CALL_S	W.GNUM2
*W.ROUGH    CALL_S	W.GNUM2
*W.HOT      CALL_S	W.GNUM2
*W.COLD     CALL_S	W.GNUM2
*W.SLIPPERY CALL_S	W.GNUM2
*W.FURRY    CALL_S	W.GNUM2
*W.CLAMY    CALL_S	W.GNUM2
       
       DS.B     2*7
  
W.SOFT     CALL_S	W.GNUM2
*W.HARD     CALL_S	W.GNUM2
*W.WARM     CALL_S	W.GNUM2
*W.TXSP1    CALL_S	W.GNUM2
*W.TXSP2    CALL_S	W.GNUM2
*W.TXSP3    CALL_S	W.GNUM2
*W.TXSP4    CALL_S	W.GNUM2
*W.TXSP5    CALL_S	W.GNUM2
       
       DS.B     2*7
  
W.GOT      CALL_S	W.GNUM2
W.FXTIT    CALL_S	W.GNUM2
W.CON      CALL_S	W.GNUM2
W.ANYT     CALL_S	W.GNUM3
W.FAPART   CALL_S	W.GNUM3
W.SEPAWY   CALL_S	W.GNUM3
W.NOT      CALL_S	W.GNUM3
W.DFLESS   CALL_S	W.GNUM3
W.DFND     CALL_S	W.GNUM3
W.DEFET    CALL_S	W.GNUM3
W.TSOFT    CALL_S	W.GNUM3
W.THANK    CALL_S	W.GNUM3
W.UNCON    CALL_S	W.GNUM3
W.ASLEP    CALL_S	W.GNUM3
W.AETARG   CALL_S	W.GNUM3
W.OFF      CALL_S	W.GNUM3
W.FINSH    CALL_S	W.GNUM3
W.LOCKED   CALL_S	W.GNUM3
W.FUN      CALL_S	W.GNUM3
W.INTER    CALL_S	W.GNUM3
W.CRUNCH   CALL_S	W.GNUM3
W.WNTMVE   CALL_S	W.GNUM3
W.AHEM     CALL_S	W.GNUM3
W.CNTHEA  CALL_S	W.GNUM3

*--------------------------------
*
*  SRC.ADV.MSGWRITE1C
*
*--------------------------------
 
W.FXPERM   CALL_S	W.GNUM3
W.FITS     CALL_S	W.GNUM3
*W.COP0     CALL_S	W.GNUM3
       
       DS.B     2
  
W.COP1     CALL_S	W.GNUM3
*W.COP2     CALL_S	W.GNUM3
*W.COP3     CALL_S	W.GNUM3
*W.COP4     CALL_S	W.GNUM3
*W.COP5     CALL_S	W.GNUM3
       
       DS.B     8
  
W.COP6     CALL_S	W.GNUM3
*W.COP7     CALL_S	W.GNUM3
*W.COP8     CALL_S	W.GNUM3
*W.COP9     CALL_S	W.GNUM3
*W.COP10    CALL_S	W.GNUM3
*W.COP11    CALL_S	W.GNUM3
       
       DS.B     10
  
W.COP12    CALL_S	W.GNUM3
*W.COP13    CALL_S	W.GNUM3
*W.COP14    CALL_S	W.GNUM3
 
       DS.B     4
 
W.COP15    CALL_S	W.GNUM3
W.IFUSAY   CALL_S	W.GNUM3
*W.COP17    CALL_S	W.GNUM3
  
       DS.B     2
 
W.TAPDCE   CALL_S	W.GNUM3
*W.NODO1    CALL_S	W.GNUM3
*W.NODO2    CALL_S	W.GNUM3
*W.NODO3    CALL_S	W.GNUM3
*W.NODO4    CALL_S	W.GNUM3
*W.NODO5    CALL_S	W.GNUM3
*W.NODO6    CALL_S	W.GNUM3
*W.NODO7    CALL_S	W.GNUM3
  
       DS.B     2*7
       
W.NOTYET   CALL_S	W.GNUM3
W.NOTIMP   CALL_S	W.GNUM3
W.OUTWEI   CALL_S	W.GNUM3
W.SHIPS    CALL_S	W.GNUM3
W.RBEARD     CALL_S	W.GNUM3
W.MUNCH      CALL_S	W.GNUM3
W.PUFF       CALL_S	W.GNUM3
W.NEMPTY     CALL_S	W.GNUM3
W.ONLY       CALL_S	W.GNUM3
W.ATMOMT     CALL_S	W.GNUM3
W.IT         CALL_S	W.GNUM3
W.HE         CALL_S	W.GNUM3
LBL.SHE        NOP             ;CAN'T CALL_STO NEXR INST
*W.HER        CALL_S	W.GNUM3
W.GNUM3    BRA    W.GNUM
*W.HIM        CALL_S	W.GNUM3
W.THEY       CALL_S	W.GNUM3
W.THEM       CALL_S	W.GNUM3
W.MSTBE      CALL_S	W.GNUM3
W.HASSLE     CALL_S	W.GNUM3
W.EH         CALL_S	W.GNUM3
W.TTHERE     CALL_S	W.GNUM3
W.SILNT      CALL_S	W.GNUM3
W.WWAY       CALL_S	W.GNUM3
W.VPSYC      CALL_S	W.GNUM3
W.PUTON      CALL_S	W.GNUM3
W.AYKILL     CALL_S	W.GNUM3
W.BEATRB     CALL_S	W.GNUM3
W.CONTO      CALL_S	W.GNUM3
W.ANYTH      CALL_S	W.GNUM3
W.TASTES     CALL_S	W.GNUM3
W.REMOVE     CALL_S	W.GNUM3
W.NINSID    CALL_S	W.GNUM3
W.AINSID     CALL_S	W.GNUM3
W.HITS       CALL_S	W.GNUM3
W.OUCH       CALL_S	W.GNUM3
W.WAKES      CALL_S	W.GNUM3
W.ASLEEP     CALL_S	W.GNUM3
W.TPASS      CALL_S	W.GNUM3
W.ANOY       CALL_S	W.GNUM3
W.FIDDLE     CALL_S	W.GNUM3
W.GIVEUP     CALL_S	W.GNUM3
W.NOVEL      CALL_S	W.GNUM3
W.NMOUTH     CALL_S	W.GNUM3
W.PUSH       CALL_S	W.GNUM3
W.TOGTY      CALL_S	W.GNUM3
W.THEMAL     CALL_S	W.GNUM3
W.INTOWO     CALL_S	W.GNUM3

*--------------------------------
*
*  SRC.ADV.MSGWRITE1D   
*
*--------------------------------
 
W.NCONCE     CALL_S	W.GNUM3
W.SAYTO      CALL_S	W.GNUM3
W.IMPOLI     CALL_S	W.GNUM3
W.THOUGH     CALL_S	W.GNUM3
W.HELLO      CALL_S	W.GNUM3
W.HRD2BE     CALL_S	W.GNUM3
W.KNOWNO     CALL_S	W.GNUM3
W.REALWN     CALL_S	W.GNUM3
W.YDESIR     CALL_S	W.GNUM3
W.CAREWN     CALL_S	W.GNUM3
W.FALSEI     CALL_S	W.GNUM3
W.TRUEI      CALL_S	W.GNUM3
W.ERROR      CALL_S	W.GNUM3
W.FERG       CALL_S	W.GNUM3
W.FOR        CALL_S	W.GNUM3
W.GIVE       CALL_S	W.GNUM3
W.FLOOK      CALL_S	W.GNUM3
W.CANTH      CALL_S	W.GNUM3
W.NO.TNG     CALL_S	W.GNUM3
W.REBUIL     CALL_S	W.GNUM3
W.SOMETH     CALL_S	W.GNUM3
W.WHICH      CALL_S	W.GNUM3
W.BTINA      CALL_S	W.GNUM3
W.ACON       CALL_S	W.GNUM3
W.NWHERE     CALL_S	W.GNUM3
W.IDNATA     CALL_S	W.GNUM3
W.SAYS       CALL_S	W.GNUM3
W.PLUSE      CALL_S	W.GNUM3
W.MAD        CALL_S	W.GNUM3
W.HYF        CALL_S	W.GNUM3
W.NOIDEA     CALL_S	W.GNUM5
W.WYLTK      CALL_S	W.GNUM5
W.NOTOBV     CALL_S	W.GNUM5
W.STQ        CALL_S	W.GNUM5
W.IDNK       CALL_S	W.GNUM5
W.BECOF      CALL_S	W.GNUM5
W.BECAUS     CALL_S	W.GNUM5
W.EMMM       CALL_S	W.GNUM5
W.TNNICE     CALL_S	W.GNUM5
W.FSALE      CALL_S	W.GNUM5
W.AYOURS     CALL_S	W.GNUM5
W.NTENDE     CALL_S	W.GNUM5
W.STRANG     CALL_S	W.GNUM5
W.NDEAL      CALL_S	W.GNUM5
W.SO         CALL_S	W.GNUM5
W.PUT        CALL_S	W.GNUM5
W.ONGND      CALL_S	W.GNUM5
W.CNTCAR     CALL_S	W.GNUM5
W.TO         CALL_S	W.GNUM5
W.LIGHT      CALL_S	W.GNUM5
W.IDNTT      CALL_S	W.GNUM5
W.QSUIT      CALL_S	W.GNUM5
W.CNTUNL     CALL_S	W.GNUM5
W.STEADF     CALL_S	W.GNUM5
W.APEARS     CALL_S	W.GNUM5
W.2MUCH      CALL_S	W.GNUM5
W.CLOSED     CALL_S	W.GNUM5
W.1ATTIM     CALL_S	W.GNUM5
W.ROPED      CALL_S	W.GNUM5
W.TEAR       CALL_S	W.GNUM5
W.SHRED      CALL_S	W.GNUM5
W.TOO        CALL_S	W.GNUM5
W.TOUGH      CALL_S	W.GNUM5
W.ENOUGH     CALL_S	W.GNUM5
W.STRONG     CALL_S	W.GNUM5
W.NOCUT      CALL_S	W.GNUM5
W.NEASY      CALL_S	W.GNUM5
W.MINDRD     CALL_S	W.GNUM5
W.NTREAD     CALL_S	W.GNUM5
*W.CLDSHR     CALL_S	W.GNUM5
       
       DS.B     2
       
       NOP     ;EEKKK?!!!
W.GNUM5    BRA  W.GNUM
*W.TEMPTR     CALL_S	W.GNUM5
*W.IYAUPTI    CALL_S	W.GNUM5
*W.ICDOANY    CALL_S	W.GNUM5
W.CANCOP     CALL_S	W.GNUM5
W.OR         CALL_S	W.GNUM5
W.SHUTUP     CALL_S	W.GNUM5
*W.IDBELYU    CALL_S	W.GNUM5
       
       DS.B     2
       
W.MBEITI     CALL_S	W.GNUM5
W.ITSGOD     CALL_S	W.GNUM5
W.YURMIS     CALL_S	W.GNUM5
*W.FORYOU     CALL_S	W.GNUM5
  
       DS.B     2
       
W.MYPROB     CALL_S	W.GNUM5
W.ALWAYS     CALL_S	W.GNUM5
*W.IMFINE     CALL_S	W.GNUM5
       
       DS.B     2
       
W.VERYWE     CALL_S	W.GNUM5
W.NONE       CALL_S	W.GNUM5
W.NOTMUC     CALL_S	W.GNUM5
W.IHAVNT     CALL_S	W.GNUM5
W.ENGH       CALL_S	W.GNUM5
*W.COULDD     CALL_S	W.GNUM5
*W.PERHAP     CALL_S	W.GNUM5
 
       DS.B     2*2
       
W.POSSIB     CALL_S	W.GNUM5
W.UNLIKE     CALL_S	W.GNUM5
W.NOCHAN     CALL_S	W.GNUM5
W.NOTREA     CALL_S	W.GNUM5
W.NEVER      CALL_S	W.GNUM5
*W.USEBRAIN   CALL_S	W.GNUM5
       
       DS.B     2
       
W.ISPOSS     CALL_S	W.GNUM5
W.IDKYC      CALL_S	W.GNUM5
W.ASKSOM     CALL_S	W.GNUM5
W.SLIM       CALL_S	W.GNUM5
W.DONTWR     CALL_S	W.GNUM5

*--------------------------------
*
*  SRC.ADV.MSGWRITE1E
*
*--------------------------------
 
W.FUTURE     CALL_S	W.GNUM5
W.WLATER     CALL_S	W.GNUM5
W.DWAM       CALL_S	W.GNUM5
W.DEV        CALL_S	W.GNUM5
W.RIGHTS     CALL_S	W.GNUM5
W.SHOULD     CALL_S	W.GNUM5
*W.IHNI       CALL_S	W.GNUM5
       
       DS.B     2
       
W.ICHYT      CALL_S	W.GNUM5
W.ISNTRE     CALL_S	W.GNUM5
W.TWBT       CALL_S	W.GNUM5
W.INTHAI     CALL_S	W.GNUM5
W.GQUEST     CALL_S	W.GNUM5
W.FORGOT     CALL_S	W.GNUM5
W.UNLOCK     CALL_S	W.GNUM5
W.NWAY       CALL_S	W.GNUM5
W.IAM        CALL_S	W.GNUM5
W.WEIRD      CALL_S	W.GNUM5
W.GOTNON     CALL_S	W.GNUM5
W.BIDHIT     CALL_S	W.GNUM5
W.NONEED     CALL_S	W.GNUM5
W.NOONE      CALL_S	W.GNUM5
W.JSTWHT     CALL_S	W.GNUM5
W.CLICK      CALL_S	W.GNUM5
W.SQLCH      CALL_S	W.GNUM5
W.THUD       CALL_S	W.GNUM5
 
*W.VERY
*W.EXTREMELY
*W.QUITE
*W.HEAVY
*W.LIGHT
*W.LARGE
*W.SMALL
*W.TOO
               DS.B  16
W.FNOI       CALL_S    W.GNUM6
W.HFUN       CALL_S	W.GNUM6
W.BROKEN     CALL_S	W.GNUM6
W.GIVESP     CALL_S	W.GNUM6
W.ABSKIS     CALL_S	W.GNUM6
W.JUSONE     CALL_S	W.GNUM6
W.NOTIE      CALL_S	W.GNUM6
W.NORCH      CALL_S	W.GNUM6
W.FHERE      CALL_S	W.GNUM6
W.NOTAKE     CALL_S	W.GNUM6
W.NORIDE     CALL_S	W.GNUM6
W.WHAK       CALL_S	W.GNUM6
W.FALOFF     CALL_S	W.GNUM6
W.TALKME     CALL_S	W.GNUM6
W.ALRDY      CALL_S	W.GNUM6
W.YBLUKY     CALL_S	W.GNUM6
W.TRICKQ     CALL_S	W.GNUM6
W.MTMAGI     CALL_S	W.GNUM6
W.NOTSEA     CALL_S	W.GNUM6
W.ONFEET     CALL_S	W.GNUM6
W.NSO        CALL_S	W.GNUM6
W.CSOT       CALL_S	W.GNUM6
W.CSJA       CALL_S	W.GNUM6
W.NOLIE      CALL_S	W.GNUM6
W.SITUP      CALL_S	W.GNUM6
W.ASO        CALL_S	W.GNUM6
W.NOSEAT     CALL_S	W.GNUM6
W.CTEXT      CALL_S	W.GNUM6
W.ONEOF      CALL_S	W.GNUM6
W.GLARE      CALL_S	W.GNUM6
W.MAGFOR     CALL_S	W.GNUM6
W.LEAP       CALL_S	W.GNUM6
W.HAS        CALL_S	W.GNUM6
W.VANI       CALL_S	W.GNUM6
W.DEADDN     CALL_S	W.GNUM6
W.IFONLY     CALL_S	W.GNUM6
W.BURNAW     CALL_S	W.GNUM6
W.DEADED     CALL_S	W.GNUM6
W.LETOFF     CALL_S	W.GNUM6
W.PDR2       CALL_S	W.GNUM6
W.USURE      CALL_S	W.GNUM6
W.QUIT       CALL_S	W.GNUM6
W.ENSURE     CALL_S	W.GNUM6
       
W.IAGREE     CALL_S	W.GNUM6
W.4BUFS      CALL_S	W.GNUM6
W.JCHKG      CALL_S	W.GNUM6
W.WISLI      CALL_S	W.GNUM6
W.NO         CALL_S	W.GNUM6
W.MINE       CALL_S	W.GNUM6
W.FIND       CALL_S	W.GNUM6
W.GETOFF     CALL_S	W.GNUM6
W.NOTMY      CALL_S	W.GNUM6
W.THIEF      CALL_S	W.GNUM6
W.WPRI       CALL_S	W.GNUM6
W.COULD      CALL_S	W.GNUM6
W.ABOUT      CALL_S	W.GNUM6
W.WORTH      CALL_S	W.GNUM6
W.WLESS      CALL_S	W.GNUM6
W.PROBAB     CALL_S	W.GNUM6
W.OFANY      CALL_S	W.GNUM6
W.ME         CALL_S	W.GNUM6
W.PLESS      CALL_S	W.GNUM6
W.BADW       CALL_S	W.GNUM
W.GNUM6    BRA   W.GNUM
*W.ASCONT    CALL_S	W.GNUM6
*W.HAPPY     CALL_S  W.GNUM
W.HOHO       CALL_S  W.GNUM
W.UMEAN      CALL_S  W.GNUM
       
       
       
W.TEMPTR     PEA  W.GNUM5+0(PC)
       BRA.S   W.GNUM
W.IYAUPT     PEA  W.GNUM5+2(PC)
       BRA.S   W.GNUM
W.ICDOAN     PEA  W.GNUM5+4(PC)
       BRA.S   W.GNUM

*--------------------------------
*
*  SRC.ADV.MSGWRITE2
*
*
* THIS MUST FOLLOW MSGWRITE1
*      ====
*
*--------------------------------
 
       NOP     ;NEEDED!!!!!
 
W.GNUM
 
 
       MOVE.L  (A7)+,M_STACK(A4)
       PUSH_L  D1/A0
       CMP.W   #$1,PLURAL(A4)
       BLT.S   05$                ;NORMAL
       SUB.W   #$2,PLURAL(A4)     ;ADJUST
       BRA.S   10$                ;FIXED
05$
       CLR.W   PLURAL(A4)
       BTST    #0,(A0)
       BEQ.S   10$
       NOT.W   PLURAL(A4)         ;MOVE IN -1
10$
       LEA     W.GNUMSTART(PC),A0
       MOVE.L  M_STACK(A4),D1
       SUB.L   A0,D1
       LSR.L   #1,D1
       DO	P.MSG
       CLR.W   PLURAL(A4)   
       PULL_L  D1/A0
       RET
  
*--------------------------------
*
*  EXTRA TEXT
* 
*--------------------------------
  
       
W.GLOW
       PRINT  'GLOWING'
       RET

   END
