***************************************************************************
*
*
*	fred23jr output from file '../guild'*
*
***************************************************************************

		SECTION		"ADV",CODE

*--------------------------------
*
*  SRC.ADV.DATA2
*
*--------------------------------
 
	include "equates.i"
	include	"macros.i"
	include	"roomequ.i"
	include	"nounequ1.i"


	XDEF	PSUDAT,NPC.DATA,NPC.LIST

	XDEF	ValueTable




* Pseudo define (starts list of rooms containing object)

PS_DEF      MACRO    * noun identifier

            DC.B     0                    ;terminate previous list
			IFNE	GENERIC
	    DC.B	N\1>>8
	    DC.B	N\1&$FF
			ENDC
P_\1        EQU      *-PSUDAT             ;data to go in noundata
            XDEF     P_\1                 ;for linker

            ENDM

* Pseudo continue (the actual list of rooms)

PS_CONT     MACRO    * room [,room..]     ;NB max 9 rooms per line!

            PS_ROOM  \1
            PS_ROOM  \2
            PS_ROOM  \3
            PS_ROOM  \4
            PS_ROOM  \5
            PS_ROOM  \6
            PS_ROOM  \7
            PS_ROOM  \8
            PS_ROOM  \9

            ENDM

PS_ROOM     MACRO    * room               ;encode for one room (if there)

           IFNC     '\1',''

            DC.B     RN\1

           ENDC

            ENDM


PSUDAT


	PS_DEF	MOORING
	PS_CONT	BOAT,JETTY

	PS_DEF	DRAWBRIDGE
	PS_CONT	SCRUB3,GATEHOUSE

	PS_DEF	BOAT2
	PS_CONT	BOAT,JETTY

	PS_DEF	JETTY2
	PS_CONT	BOAT,JETTY,SCRUB1,SCRUB2,FIELD

	PS_DEF	RIVER
	PS_CONT	BOAT,JETTY,SCRUB1,SCRUB2,FOREST2,FOREST3,FOREST4,FIELD

	PS_DEF	WATER
	PS_CONT	BOAT,JETTY,SCRUB1,SCRUB2,FOREST2,FOREST3,FOREST4,FIELD
	PS_CONT	WELL1,WELL2,WELL3,TUNNEL,SUMP,BANK,CRAB1,CAVE2
	PS_CONT	CAVE1,CAVE3,RRM,RVR,TPWFL,BHSE,DRM5,PASSAGE3

	PS_DEF	WHEATFIELD
	PS_CONT	JETTY,SCRUB2,SCRUB3,FOREST1,FOREST3,FIELD

	PS_DEF	MOAT
	PS_CONT	SCRUB3,SCRUB1,PASSAGE3,YARD

	PS_DEF	CASTLE
	PS_CONT	HGROUND,SCRUB3,SCRUB1,PASSAGE3,YARD

	PS_DEF	COPSE
	PS_CONT	SCRUB2,SCRUB3,FOREST1,FOREST2,FOREST3,FOREST4,FIELD,HGROUND

	PS_DEF	WOOD
	PS_CONT	SCRUB3,FOREST1,FIELD,HGROUND

	PS_DEF	HILL
	PS_CONT	SCRUB3,FOREST1,FOREST2,HGROUND

	PS_DEF	TREES
	PS_CONT	SCRUB3,FIELD,HGROUND,FOREST1,FOREST2,FOREST3,FOREST4

	PS_DEF	COUNTER
	PS_CONT	SHOP2,SHOP3

	PS_DEF	LAKE
	PS_CONT	BHSE,DRM5

	PS_DEF	WALL1
	PS_CONT	ROOM1,GALLERY,KITCHEN,LOUNGE,HALL1,HALL2,QUARTERS,BEDROOM1
	PS_CONT	GATEHOUSE,MILL1,STABLE,LAB,BEDROOM2,CORRIDOR1,CORRIDOR2,CORRIDOR3
	PS_CONT	CORRIDOR4,LIBRARY,BATHROOM,ROOM3,ROOM4,BEDROOM3,CELLAR,SWAY5
	PS_CONT	PASSAGE1,ROOM2,ROOM9,ENTR,PSG2,PSG4,PSG7,FRK
	PS_CONT	SHOP1,SHOP2,SHOP3,CEMTR,TJUNC1,TJUNC2,TJUNC3,HSE
	PS_CONT	OFFIS,PSG7,AVRE,GDN2,CAGE,RMUD,FNRM,STPS
	PS_CONT	BHSE,DRM1,DRM2,DRM3,DRM4,DRM5,RRM,RVR
	PS_CONT	TPWFL,CAVE1,CAVE2,FACE,CAVE3,CRAB1,SHAFT1,BANK
	PS_CONT	SUMP,TUNNEL,WELL1,WELL2,WELL3,ACHAM,TEMPLE,STAIR1
	PS_CONT	STAIR2,STAIR3,STAIR4,SWAY1,SWAY2,SWAY3,SWAY4,WHITESQUARE
	PS_CONT	BLACKSQUARE,CRYPT,LIBRARY2,ORGANROOM,SHRINE,YARD,KBANK,INBANK
	PS_CONT	MANOFFIS,TILL1

	PS_DEF	SKY
	PS_CONT	BOAT,JETTY,SCRUB1,SCRUB2,SCRUB3,FOREST1,FOREST2,FOREST3
	PS_CONT	FOREST4,FIELD,HGROUND,YARD,PATH,GDN1,PASSAGE3

	PS_DEF	DOOR1
	PS_CONT	PASSAGE1,SWAY5

	PS_DEF	RATS
	PS_CONT	CELLAR,SWAY5

	PS_DEF	STEPS
	PS_CONT	PASSAGE1,STPS,SWAY5,STAIR1,STAIR2,STAIR3,STAIR4,SWAY1
	PS_CONT	SWAY2,SWAY3,SWAY4

	PS_DEF	RATWATER
	PS_CONT	CELLAR,SWAY5

	PS_DEF	JUNK
	PS_CONT	ROOM2,PASSAGE3

	PS_DEF	GRID
	PS_CONT	REDSQUARE1,REDSQUARE2,ORANGESQUARE1,ORANGESQUARE2,YELLOWSQUARE1,YELLOWSQUARE2,GREENSQUARE1,BLUESQUARE1
	PS_CONT	BLUESQUARE3,INDIGOSQUARE1,INDIGOSQUARE2,INDIGOSQUARE3,VIOLETSQUARE1,VIOLETSQUARE2,BLACKSQUARE,WHITESQUARE

	PS_DEF	BLUESQUAREP
	PS_CONT	YELLOWSQUARE2,VIOLETSQUARE1,ORANGESQUARE2,REDSQUARE1

	PS_DEF	ORANGESQUAREP
	PS_CONT	REDSQUARE2,WHITESQUARE,INDIGOSQUARE2,VIOLETSQUARE1,VIOLETSQUARE2,BLUESQUARE3,INDIGOSQUARE3

	PS_DEF	YELLOWSQUAREP
	PS_CONT	INDIGOSQUARE2,VIOLETSQUARE1,ORANGESQUARE1,VIOLETSQUARE2,BLUESQUARE1,INDIGOSQUARE3,BLUESQUARE3

	PS_DEF	VIOLETSQUAREP
	PS_CONT	REDSQUARE1,REDSQUARE2,YELLOWSQUARE1,YELLOWSQUARE2,BLUESQUARE1,ORANGESQUARE1,ORANGESQUARE2,INDIGOSQUARE3
	PS_CONT	BLUESQUARE3

	PS_DEF	REDSQUAREP
	PS_CONT	BLACKSQUARE,WHITESQUARE,INDIGOSQUARE1,VIOLETSQUARE1,VIOLETSQUARE2,INDIGOSQUARE3,BLUESQUARE3,GREENSQUARE1
	PS_CONT	YELLOWSQUARE1

	PS_DEF	GREENSQUAREP
	PS_CONT	YELLOWSQUARE1,YELLOWSQUARE2,INDIGOSQUARE2,ORANGESQUARE2

	PS_DEF	INDIGOSQUAREP
	PS_CONT	BLACKSQUARE,REDSQUARE2,YELLOWSQUARE2,BLUESQUARE1,BLUESQUARE3,REDSQUARE1

	PS_DEF	BLACKSQUAREP
	PS_CONT	INDIGOSQUARE1,VIOLETSQUARE1

	PS_DEF	WHITESQUAREP
	PS_CONT	ORANGESQUARE1,VIOLETSQUARE2

	PS_DEF	DOOR4
	PS_CONT	LIBRARY2,SHRINE

	PS_DEF	ROPE
	PS_CONT	CAVE2,CAVE3

	PS_DEF	BARS
	PS_CONT	RRM,ROOM9

	PS_DEF	DOOR5
	PS_CONT	PSG7,OFFIS

	PS_DEF	DOOR6
	PS_CONT	CAGE,PSG7

	PS_DEF	DOOR7
	PS_CONT	SHOP1,SHOP2

	PS_DEF	LADDER
	PS_CONT	CAVE1,TPWFL

	PS_DEF	PRIVDOOR
	PS_CONT	TJUNC3,OFFIS

	PS_DEF	OUTSIDE
	PS_CONT	BOAT,JETTY,SCRUB1,SCRUB2,SCRUB3,FOREST1,FOREST2,FOREST3
	PS_CONT	FOREST4,FIELD,HGROUND,YARD,PATH,GDN1

	PS_DEF	INSIDE
	PS_CONT	GATEHOUSE,BEDROOM1,QUARTERS,KITCHEN,HALL1,HALL2,YARD,PATH
	PS_CONT	STABLE,LOUNGE,GALLERY,ROOM1,PASSAGE1,SWAY5,CELLAR,ROOM2
	PS_CONT	CORRIDOR1,CORRIDOR2,CORRIDOR3,CORRIDOR4,LIBRARY,BATHROOM,BEDROOM2,BEDROOM3
	PS_CONT	PASSAGE3

	PS_DEF	WETPLACES
	PS_CONT	SUMP,BANK,SHAFT1,CRAB1,CAVE2,FACE,CAVE1,CAVE3
	PS_CONT	RVR,TPWFL,BHSE

	PS_DEF	IGATE
	PS_CONT	FRK,CEMTR

	PS_DEF	STAIRCASE
	PS_CONT	HALL2,CORRIDOR1

	PS_DEF	POPENING
	PS_CONT	FOREST4,HGROUND,YARD,PASSAGE1,LAB,CAVE2,CAVE1,RVR
	PS_CONT	DRM1,DRM3,PASSAGE3,MANOFFIS

	PS_DEF	PENTRANCE
	PS_CONT	CORRIDOR2,CORRIDOR4,FACE,FIELD

	PS_DEF	PPASSAGE
	PS_CONT	ROOM2,FRK

	PS_DEF	PDUST
	PS_CONT	PASSAGE1,PASSAGE3,LIBRARY2,ROOM2,CRYPT

	PS_DEF	PCORNER
	PS_CONT	TEMPLE,WHITESQUARE,BLACKSQUARE,OFFIS,DRM3

	PS_DEF	PFACE
	PS_CONT	CAVE1,PSG2,TPWFL

	PS_DEF	PWHEAT
	PS_CONT	JETTY,SCRUB3,FOREST1,SCRUB2,FIELD,FOREST3

	PS_DEF	STABLEDOOR
	PS_CONT	STABLE,PATH

	PS_DEF	OAKDOOR
	PS_CONT	KBANK,INBANK

	PS_DEF	QUEUE1
	PS_CONT	INBANK,TILL1

	PS_DEF	QUEUE2
	PS_CONT	INBANK,TILL1

	PS_DEF	MANDOOR
	PS_CONT	INBANK,MANOFFIS

	PS_DEF	COUNTER2
	PS_CONT	TILL1,INBANK

	PS_DEF	WALL2
	PS_CONT	PASSAGE3

	PS_DEF	TILL2
	PS_CONT	INBANK,TILL1

	PS_DEF	STAFF
	PS_CONT	INBANK,TILL1

	PS_DEF	FINBANK
	PS_CONT	TILL1,INBANK

	PS_DEF	BGLASS
	PS_CONT	TILL1,INBANK

	PS_DEF	PEOPLE
	PS_CONT	INBANK,TILL1

	PS_DEF	STREAM
	PS_CONT	TPWFL,RRM,RVR


	DC.B	0
	ALIGN
ValueTable
	DC.W	55,NLUTE
	DC.W	55,NCHEQUE
	DC.W	5,NNOTE
	DC.W	2,NPIECE


     DC.L    0                   ;long word terminator


*--------------------------------
*
* NPC ADDITIONAL DATA:
*
* BYTE #0 - MOTIVATION MODIFIER
*           FOR NPC, THRESHOLD 7F
*           (NOT USED (YET)) 
*
* BYTE #1 - NO. OF QUESTIONS TILL
*           NPC GETS PISSED OFF
*           (ALSO N/A (YET))
*
* BYTE #2 - EMOTION,ARTICLE,
*           CLOTHING & SEX
*
*     TOP NIBBLE - 0-F
*  
* 0 - NULL     1 - HAPPY
* 2 - ANGRY    3 - VIOLENT
* 4 - ASLEEP   5 - UNCONSIOUS
* 6 - PEACEFUL 7 - EXCITED
* 8 - FRIENDLY 9 - DRUNK
* A - SAD      B - TIRED
* C - SUFFERING
*
*
*     BOTTOM NIBBLE:
*
* BIT #0 - SEX: MALE=1,FEMALE=0
* BIT #1 - CLOTHING: 1=SUPPRESS
* BIT #2 - 1=> is animal
* BIT #3 - ARTICLE - 
*
* 1 - NONE E.G. HONEST JOHN,ERIK
* 0 - NORM E.G. A GURU/THE GURU
*
*
* BYTE #3 - NPC PAUSED (IF <0)
*
*
*--------------------------------
 
   
NPC.DATA
 
       include "npcdata.i"
        
	DC.L	0

NPC.LIST

	include	"npclist.i"
	DC.L	0
      END


* produced on Tue Jun 12 09:38:16 2018

* checksum = 5cfc6023
