nway_door		EQU	-1
nway_wall		EQU	-2
nway_riverbank		EQU	-3
nway_trees		EQU	-4
nway_castlemoat		EQU	-5
nway_vanes		EQU	-6
nway_toll		EQU	-7
nway_shop		EQU	-8
nway_slope		EQU	-9
nway_death		EQU	-10
nway_river		EQU	-11
nway_lake		EQU	-12
nway_railings		EQU	-13
nway_pigeon		EQU	-14
nway_rockface		EQU	-15
nway_fridge		EQU	-16
nway_ironbars		EQU	-17
nway_misc1		EQU	-18
nway_misc2		EQU	-19
nway_misc3		EQU	-20
nway_misc4		EQU	-21
nway_misc5		EQU	-22
nway_misc6		EQU	-23
