******************************************************
*
*	%W%
*	%G%
*
******************************************************

******************************************************
*
*      Pictnames.asm
*
*      Included by Datafile for the names of the piccies.
*
******************************************************


		IFEQ	TITLEPIC
MAXNAMES:       EQU     29
		ENDC

		IFNE	TITLEPIC
MAXNAMES	EQU	30
		ENDC

OkOk	SET	FALSE

                IFNE    PROD!PROD_TEST
OkOk	SET	TRUE
		ENDC

		IFNE	AMIGA512!OkOk

NAMETAB:        DC.W    YARD-NAMETAB
                DC.W    CORRIDOR-NAMETAB
                DC.W    MUSIC-NAMETAB
                DC.W    RIVER-NAMETAB
                DC.W    LOUNGE-NAMETAB
                DC.W    BILLIARD-NAMETAB
		DC.W	HOTHOUSE-NAMETAB
		DC.W	SKELETON-NAMETAB
		DC.W	INTEMPLE-NAMETAB
		DC.W	ANTECHAM-NAMETAB
		DC.W	WFIELD-NAMETAB
		DC.W	BOATS-NAMETAB
		DC.W	COALROOM-NAMETAB
		DC.W	STAIRWAY-NAMETAB
		DC.W	TEMPLE-NAMETAB
		DC.W	CASTLE-NAMETAB	
		DC.W	RAINBOWR-NAMETAB	
		DC.W	CEMETERY-NAMETAB	
		DC.W	FOREST2-NAMETAB	
		DC.W	SHOP-NAMETAB	
		DC.W	BANK1-NAMETAB
		DC.W	OUTBANK-NAMETAB
		DC.W	BANKMAN-NAMETAB
		DC.W	CRYPT-NAMETAB
		DC.W	KITCHEN-NAMETAB
		DC.W	SUMP-NAMETAB
		DC.W	TEMPCORR-NAMETAB
		DC.W	WINDMILL-NAMETAB
		DC.W	ORGAN-NAMETAB

; 4 new pictures from the collection
                DC.W    HILL_PIC-NAMETAB
                DC.W    MACAW_PIC-NAMETAB
                DC.W    SHRINE_PIC-NAMETAB
                DC.W    STABLE_PIC-NAMETAB


		IFNE	TITLEPIC
		DC.W	TITLE-NAMETAB
		ENDC
                
LASTENTRY:

		IFEQ	AMIGA512

YARD:		DC.B	'YARD.FIN',0
CORRIDOR:	DC.B	'CORRIDOR.FIN',0
MUSIC:		DC.B	'MUSIC.FIN',0
RIVER:		DC.B	'RIVER.FIN',0
LOUNGE:		DC.B	'LOUNGE.FIN',0
BILLIARD:	DC.B	'BILLIARD.FIN',0
HOTHOUSE:	DC.B	'HOTHOUSE.FIN',0
SKELETON:	DC.B	'SKELETON.FIN',0
INTEMPLE:	DC.B	'INTEMPLE.FIN',0
ANTECHAM:	DC.B	'ANTECHAM.FIN',0
WFIELD:		DC.B	'WFIELD.FIN',0
BOATS		DC.B	'BOATS.FIN',0
COALROOM	DC.B	'COALROOM.FIN',0
STAIRWAY	DC.B	'STAIRWAY.FIN',0
TEMPLE		DC.B	'TEMPLE.FIN',0
CASTLE		DC.B	'CASTLE.FIN',0
RAINBOWR	DC.B	'RAINBOWR.FIN',0
CEMETERY	DC.B	'CEMETERY.FIN',0
FOREST2		DC.B	'FOREST2.FIN',0
SHOP		DC.B	'SHOP.FIN',0
BANK1		DC.B	'BANK1.FIN',0
OUTBANK		DC.B	'OUTBANK.FIN',0
BANKMAN		DC.B	'BANKMAN.FIN',0
CRYPT		DC.B	'CRYPT.FIN',0
KITCHEN		DC.B	'KITCHEN.FIN',0
SUMP		DC.B	'SUMP.FIN',0
TEMPCORR	DC.B	'TEMPCORR.FIN',0
WINDMILL	DC.B	'WINDMILL.FIN',0
ORGAN		DC.B	'ORGAN.FIN',0

; 4 new pictures from the collection
HILL_PIC        DC.B    'HILL',0
MACAW_PIC       DC.B    'MACAW',0
SHRINE_PIC      DC.B    'SHRIN',0
STABLE_PIC      DC.B    'STABL',0

		ENDC

		IFNE	AMIGA512

YARD:		DC.B	'guild4',0
CORRIDOR:	DC.B	'guild5',0
MUSIC:		DC.B	'guild6',0
RIVER:		DC.B	'guild7',0
LOUNGE:		DC.B	'guild8',0
BILLIARD:	DC.B	'guild9',0
HOTHOUSE:	DC.B	'guild10',0
SKELETON:	DC.B	'guild11',0
INTEMPLE:	DC.B	'guild12',0
ANTECHAM:	DC.B	'guild13',0
WFIELD:		DC.B	'guild14',0
BOATS		DC.B	'guild15',0
COALROOM	DC.B	'guild16',0
STAIRWAY	DC.B	'guild17',0
TEMPLE		DC.B	'guild18',0
CASTLE		DC.B	'guild19',0
RAINBOWR	DC.B	'guild20',0
CEMETERY	DC.B	'guild21',0
FOREST2		DC.B	'guild22',0
SHOP		DC.B	'guild23',0
BANK1		DC.B	'guild24',0
OUTBANK		DC.B	'guild25',0
BANKMAN		DC.B	'guild26',0
CRYPT		DC.B	'guild27',0
KITCHEN		DC.B	'guild28',0
SUMP		DC.B	'guild29',0
TEMPCORR	DC.B	'guild30',0
WINDMILL	DC.B	'guild31',0
ORGAN		DC.B	'guild32',0

		ENDC

		IFNE	TITLEPIC
TITLE:		DC.B	'TITLE.FIN',0
		ENDC

		ENDC
